services:
  kotlinapp:
    container_name: kotlinapp
    image: aimarchirico/kotlinapp:latest
    build:
        context: .
        dockerfile: Dockerfile
        args:
          DB_URL: ${DB_URL}
          DB_USER: ${POSTGRES_USER}
          DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
    pgdata: {}